default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: stock_dev

test:
  <<: *default
  database: stock_test

production:
  <<: *default
  database: stock_prod
